### ISSUE TITLE
I don't know if its just me but the performance is insanely impacted.

### ISSUE THREAD

**Issue by Shockshwat** [allenpoon/youtube-replayer#1]
Ok so i have a MacBook pro 2012 version, and a desktop. On the desktop i don;t notice performance issues on my desktop(I3-10105F) but on the MacBook pro the browser usage skyrockets from 5-4% to 71%-81%

**Comment by allenpoon** [comment]
It is because the YouTube is changed a lot which make my plugin cannot completed the initialization. The script will re-run immediately so the problem occur.

I just fixed the problem in release [v12.1](https://github.com/allenpoon/youtube-enhancer/releases/tag/v12.1). Please check the problem whether fixed or not. Thanks.

**Comment by Shockshwat** [comment]
Thanks it works now
